version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=808143511161.dkr.ecr.us-east-2.amazonaws.com/demo
  build:
    commands:
      - echo Building the docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:demo
  post_build:
    commands:
      - echo Pushing the docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:demo
      - echo Writing image definitions file...
      - printf '[{"name":"demo-service","imageUri":"%s"}]' $REPOSITORY_URI:demo > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
