version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=808143511161.dkr.ecr.us-east-2.amazonaws.com/demo
  build:
    commands:
      - echo Building the docker image...
      - docker build -t 808143511161.dkr.ecr.us-east-2.amazonaws.com/demo:latest .
      - docker tag 808143511161.dkr.ecr.us-east-2.amazonaws.com/demo:latest 808143511161.dkr.ecr.us-east-2.amazonaws.com/demo:demo
  post_build:
    commands:
      - echo Pushing the docker images...
      - docker push 808143511161.dkr.ecr.us-east-2.amazonaws.com/demo:latest
      - docker push 808143511161.dkr.ecr.us-east-2.amazonaws.com/demo:demo
      - echo Writing image definitions file...
      - printf '[{"name":"demo-service","imageUri":"%s"}]' 808143511161.dkr.ecr.us-east-2.amazonaws.com/demo:demo > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
